### ISSUE TITLE
node-cipher archiving

### ISSUE THREAD

**Issue by cruzdanilo** [Ansimorph/decryption-loader#58]
`node-cipher` has been archived on github.

it is not encrypting properly using the latest node version: https://github.com/nathanbuchar/node-cipher/issues/27
there is an annoying warning since node 12: https://github.com/nathanbuchar/node-cipher/issues/26

what is on the roadmap for this loader?

**Comment by Ansimorph** [comment]
Oh, I didn't expect that. That's pretty sad, given node-cipher still has lots of users.

This loader is not very tightly coupled to node-cipher in code. I'll explore using another encryption cli in a backwards-compatible manner.

**Comment by Ansimorph** [comment]
This release removed the dependency on node-cipher, since it is not actively maintained any longer.
decryption-loader now includes a CLI for encryption. This CLI is not backwards compatible to node-cipher, because it used createCipheriv instead of the deprecated createCipher.
This means files have to be re-encrypted for this version.

**Comment by cruzdanilo** [comment]
awesome work man! thank you very much.
